# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - math-mentor

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: azure/setup-python@v5
        with:
          python-version: '3.14'

      - name: Create and Start virtual environment and Install dependencies
        run: |
          # Change directory to your agent folder to install requirements
          cd math-mentor-agent
          python -m venv antenv
          source antenv/bin/activate
          pip install -r requirements.txt
                
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          # We only upload the contents of the agent folder to the root of the artifact
          path: |
            math-mentor-agent/
            !math-mentor-agent/antenv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write 
      contents: read 

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          # Make sure these secret names match exactly what you have in GitHub Secrets
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'math-mentor'
          slot-name: 'Production'
